// Automatically generated by flapigen
package army.warfare.skiter;


public enum GfxLayer {
    AUTO(0),
    CPU(1),
    SKIA_CPU(2),
    SKIA_OPENGL(3);

    private final int value;
    GfxLayer(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static GfxLayer fromInt(int x) {
        switch (x) {
            case 0: return AUTO;
            case 1: return CPU;
            case 2: return SKIA_CPU;
            case 3: return SKIA_OPENGL;
            default: throw new Error("Invalid value for enum GfxLayer: " + x);
        }
    }
}
