// Automatically generated by flapigen
package army.warfare.skiter;


public enum KeyboardStates {
    CONTROL_KEY_PRESSED(0),
    SHIFT_KEY_PRESSED(1),
    ALT_KEY_PRESSED(2);

    private final int value;
    KeyboardStates(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static KeyboardStates fromInt(int x) {
        switch (x) {
            case 0: return CONTROL_KEY_PRESSED;
            case 1: return SHIFT_KEY_PRESSED;
            case 2: return ALT_KEY_PRESSED;
            default: throw new Error("Invalid value for enum KeyboardStates: " + x);
        }
    }
}
