// Automatically generated by flapigen
package army.warfare.skiter;


public final class KeyboardStates {

    private KeyboardStates() {}
    public static int NONE_DOWN = 0;
    public static int CTRL_DOWN = 0x01;
    public static int SHIFT_DOWN = 0x02;
    public static int ALT_DOWN = 0x04;
}