// Automatically generated by flapigen
package army.warfare.skiter;


public enum KeyEvents {
    KEY_DOWN(0),
    KEY_UP(1),
    KEY_CHAR(2);

    private final int value;
    KeyEvents(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static KeyEvents fromInt(int x) {
        switch (x) {
            case 0: return KEY_DOWN;
            case 1: return KEY_UP;
            case 2: return KEY_CHAR;
            default: throw new Error("Invalid value for enum KeyEvents: " + x);
        }
    }
}
