// Automatically generated by flapigen
package army.warfare.skiter;


public final class Library {

    private Library() {}

    public static Library bundled() throws Exception {
        long ret = do_bundled();
        Library convRet = new Library(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_bundled() throws Exception;

    public static Library path(String path) {
        long ret = do_path(path);
        Library convRet = new Library(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_path(String path);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Library(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
    static { System.loadLibrary("skiter"); }
}