// Automatically generated by flapigen
package army.warfare.skiter;


public final class LoadResult {

    private LoadResult() {}
    public static int IGNORED = -1;
    public static int LOAD_DEFAULT = 0;
    public static int LOAD_DISCARD = 1;
    public static int LOAD_DELAYED = 2;
    public static int LOAD_MYSELF = 3;
}