// Automatically generated by flapigen
package army.warfare.skiter;


public enum MouseEvents {
    MOUSE_MOVE(0),
    MOUSE_UP(1),
    MOUSE_DOWN(2),
    MOUSE_WHEEL(3),
    MOUSE_CLICK(4);

    private final int value;
    MouseEvents(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MouseEvents fromInt(int x) {
        switch (x) {
            case 0: return MOUSE_MOVE;
            case 1: return MOUSE_UP;
            case 2: return MOUSE_DOWN;
            case 3: return MOUSE_WHEEL;
            case 4: return MOUSE_CLICK;
            default: throw new Error("Invalid value for enum MouseEvents: " + x);
        }
    }
}
