// Automatically generated by flapigen
package army.warfare.skiter;


public final class MouseButtons {

    private MouseButtons() {}
    public static int NONE = 0;
    public static int MAIN = 1;
    public static int PROP = 2;
    public static int MIDDLE = 3;
}