// Automatically generated by flapigen
package army.warfare.skiter;


public enum MouseButtons {
    LEFT(0),
    RIGHT(1),
    MIDDLE(2),
    NONE(3);

    private final int value;
    MouseButtons(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MouseButtons fromInt(int x) {
        switch (x) {
            case 0: return LEFT;
            case 1: return RIGHT;
            case 2: return MIDDLE;
            case 3: return NONE;
            default: throw new Error("Invalid value for enum MouseButtons: " + x);
        }
    }
}
