// Automatically generated by flapigen
package army.warfare.skiter;


public final class Options {

    public static void setLibrary(Library library) throws Exception {
        long a0 = library.mNativeObj;
        library.mNativeObj = 0;

        do_setLibrary(a0);

        JNIReachabilityFence.reachabilityFence1(library);
    }
    private static native void do_setLibrary(long library) throws Exception;

    public static void setGfxLayer(GfxLayer gfx_layer) throws Exception {
        int a0 = gfx_layer.getValue();
        do_setGfxLayer(a0);

        JNIReachabilityFence.reachabilityFence1(gfx_layer);
    }
    private static native void do_setGfxLayer(int gfx_layer) throws Exception;

    public static native void setUxTheming(boolean value) throws Exception;

    public static native void setScriptFeatures(short value) throws Exception;

    public static native void setDebugMode(boolean value) throws Exception;

    public static native void setInitScript(String script) throws Exception;

    public static native void setLogicalPixels(boolean value) throws Exception;

    private Options() {}
}